In [ ]:
import numpy as np
import pandas as pd
import requests
import csv
import sys
import os
import time

In [ ]:
https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=768&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv

SyntaxError: invalid decimal literal (<ipython-input-2-c3c401e2b666>, line 1)

In [ ]:
url = "https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=0&p=768&rg=2&cc=ALL&fmt=json"

df = pd.read_csv(url)
df.head()

HTTPError: HTTP Error 404: Not Found

Navia: Data Extraction Alternative: https://pypi.org/project/comtradeapicall/

In [ ]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)
root_path = 'drive/My Drive/ECI Research/5. Datasets/2022 Fall - Data/Country_Code.csv'

Mounted at /content/drive/

In [ ]:
!pip install --upgrade urllib3 requests

Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (2.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2023.7.22)

#  Define Variables( Remember to create local directory before you start)

In [ ]:

reporter_code_list=pd.read_csv(root_path,encoding='ISO-8859-1')["Country Code"].values
year_list=np.array([2019,2020,2021,2022])
PATH="drive/My Drive/ECI Research/5. Datasets/2022 Fall - Data/"

In [ ]:
CSV_URL

NameError: name 'CSV_URL' is not defined

In [ ]:
#Navia test to debug error

import OpenSSL.SSL

openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation

NameError: name 'openssl_init' is not defined

# Define helper functions

In [ ]:
# Function to web-scrap each country's export data from UN Comtrade and save to local directory by years.

def get_export(reporter_code,year):
    CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'

    with requests.Session() as s:
        download = s.get(CSV_URL, verify=False)
        decoded_content = download.content.decode('utf-8')
        cr = csv.reader(decoded_content.splitlines(), delimiter=',')
        my_list = list(cr)
        df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
        df.columns=["commodity_code","dollar_value"]
        # only include six-digit commodity codes
        df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
        if len(df)<20:
            raise ValueError
        df.to_csv(PATH+"/"+str(reporter_code)+".csv")
    return df

In [ ]:
import webbrowser

webbrowser.open('https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=768&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv')

# Open URL in a new browser window/tab

False

In [ ]:
webbrowser.open_new(url)

False

In [ ]:
import webbrowser
webbrowser.get("chrome").open("https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=768&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv")

Error: could not locate runnable browser

In [ ]:
mydf = comtradeapicall.previewFinalData(typeCode='C', freqCode='M', clCode='HS', period='202205',
                                             reporterCode='36', cmdCode='ALL', flowCode='M', partnerCode=None,
                                             partner2Code=None,
                                             customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                             countOnly=None, includeDesc=True)

76

In [ ]:
#Navia debugging 2
import urllib3
from urllib3.util.ssl_ import create_urllib3_context

ctx = create_urllib3_context()
ctx.load_default_certs()
ctx.options |= 0x4  # ssl.OP_LEGACY_SERVER_CONNECT

with urllib3.PoolManager(ssl_context=ctx) as http:
    r = http.request("GET", CSV_URL)
    print(r.status)

200

In [ ]:
len(reporter_code_list)

294

In [ ]:
get_export(76,2022)

SSLError: ignored

In [ ]:
import requests

url = "https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=768&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv"

# Make a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    print("Successfully opened the URL:", url)
else:
    print("Failed to open the URL. Status code:", response.status_code)

SSLError: ignored

In [ ]:
mydf = comtradeapicall.previewTarifflineData(typeCode='C', freqCode='M', clCode='HS', period='202205',
                                             reporterCode='36', cmdCode='91,90', flowCode='M', partnerCode=36,
                                             partner2Code=None,
                                             customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                             countOnly=None, includeDesc=True)

In [ ]:
year=2022
reporter_code=152
CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'
#Commented out getting list from requests and added a direct import for the csv - Jane

"""with requests.Session() as s:
  download = s.get(CSV_URL)
  decoded_content = download.content.decode('utf-8')
  cr = csv.reader(decoded_content.splitlines(), delimiter=',')
  my_list = list(cr)
  print(my_list)"""
my_list = pd.read_csv(PATH + "comtrade2021.csv")
df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
df.columns=["commodity_code","dollar_value"]
      # only include six-digit commodity codes
df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
if len(df)<20:
  raise ValueError
df.to_csv(PATH+"/"+"test"+"/"+str(reporter_code)+".csv")
#changed path to fix error & created test folder for test files for each country - Navia

In [ ]:
#test create helper func
year=2022
reporter_code=152
CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'
#Commented out getting list from requests and added a direct import for the csv - Jane

"""with requests.Session() as s:
  download = s.get(CSV_URL)
  decoded_content = download.content.decode('utf-8')
  cr = csv.reader(decoded_content.splitlines(), delimiter=',')
  my_list = list(cr)
  print(my_list)"""
my_list = pd.read_csv(PATH + "comtrade2021.csv")
df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
df.columns=["commodity_code","dollar_value"]
      # only include six-digit commodity codes
df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
if len(df)<20:
  raise ValueError
df.to_csv(PATH+"/"+"test"+"/"+str(reporter_code)+".csv")
#changed path to fix error & created test folder for test files for each country - Navia

def get_export(reporter_code,year):
    CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'

    with requests.Session() as s:
        download = s.get(CSV_URL, verify=False)
        decoded_content = download.content.decode('utf-8')
        cr = csv.reader(decoded_content.splitlines(), delimiter=',')
        my_list = list(cr)
        df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
        df.columns=["commodity_code","dollar_value"]
        # only include six-digit commodity codes
        df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
        if len(df)<20:
            raise ValueError
        df.to_csv(PATH+"/"+str(reporter_code)+".csv")
    return df

In [ ]:
CSV_URL

'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=152&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'

In [ ]:
#Navia test - successfully debugged by deleting &=csv format
def get_export(reporter_code,year):
    CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>'

    #with requests.Session() as s:
        #download = s.get(CSV_URL)
        #decoded_content = download.content.decode('utf-8')
        #cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = pd.read_csv(PATH + "senegal.csv")
    df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
    df.columns=["commodity_code","dollar_value"]
    # only include six-digit commodity codes
    df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
    if len(df)<20:
        raise ValueError
    df.to_csv(PATH+"/"+str(reporter_code)+".csv")
    return df

In [ ]:
get_export(686,2022)

     commodity_code dollar_value
2            010594          480
4            010619         2046
5            010632           80
6            010639        36282
7            010690         1098
...             ...          ...
2757         970192         2877
2758         970199       112058
2760         970210         2527
2762         970390       171152
2765         999999     13203437

[1906 rows x 2 columns]

In [ ]:
# Function to read in all csvs from local, merge into a mega csv, and save to local.

def merge_all(PATH,year_list):
    for year in year_list:
        sub_path=PATH+str(year)
        # fetch all file pathes and reporter codes
        dir_series = pd.Series(os.listdir(sub_path))
        avail_reporter_code_list=dir_series.str.split(".",expand=True)[0]

        # read in the first country
        df=pd.read_csv(sub_path+"/"+dir_series.iloc[0])[["commodity_code","dollar_value"]]
        df.columns=["commodity_code",avail_reporter_code_list.iloc[0]]

        # append all other countries to df
        for nxt in range(1,len(avail_reporter_code_list)):
            nxt_df=pd.read_csv(sub_path+"/"+dir_series.iloc[nxt])[["commodity_code","dollar_value"]]
            nxt_df.columns=["commodity_code",avail_reporter_code_list.iloc[nxt]]
            df=df.merge(nxt_df,left_on='commodity_code', right_on='commodity_code',how='outer')
        print(year)
        df.fillna(0,inplace=True)
        df.to_csv(sub_path+"_mega.csv")
    return 200

In [ ]:
    SERVICE_URL="https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps="+str(year)+"&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>"
SERVICE_URL

'https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps=2020&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>'

In [ ]:
# Function to add a service column to the mega csv and save to local
def get_service(year=2021):
    SERVICE_URL="https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps="+str(year)+"&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>"
    #with requests.Session() as s:
        #download = s.get(SERVICE_URL)
        #decoded_content = download.content.decode('utf-8')
        #cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
    df=pd.DataFrame(np.array(my_list))
    df=df.iloc[1:,[1,8,20]]
    df.columns=["year","reporter_code","dollar_value"]
    return df

In [ ]:
get_service(year=2022)

NameError: ignored

In [ ]:
#Navia re-coded version

def get_service(year=2021):
    SERVICE_URL="https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps="+str(year)+"&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>"
    #with requests.Session() as s:
        #download = s.get(CSV_URL)
        #decoded_content = download.content.decode('utf-8')
        #cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = pd.read_csv(PATH + "comtrade2021.csv")
    df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
    df.columns=["commodity_code","dollar_value"]
    # only include six-digit commodity codes
    df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
    if len(df)<20:
        raise ValueError
    df.to_csv(PATH+"/"+str(reporter_code)+".csv")
    return df

In [ ]:
https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps=2022

# Save all countries' export data individually to the PATH folder

for reporter_code in reporter_code_list:
    for year in year_list:
        try:
            get_export(reporter_code,year)
            print(".",end="")
        except KeyboardInterrupt:
            raise
        except:
            print("X",end="")
            pass

In [ ]:

index=np.where(reporter_code_list==784)[0][0]
print(index)
for reporter_code in reporter_code_list[index:]:
    for year in year_list:
      if os.path.exists(PATH+str(year)+"/"+str(reporter_code)+".csv")==False:
        time.sleep(10)
        try:
            get_export(reporter_code,year)
            print(".",end="")
        except KeyboardInterrupt:
            raise
        except:
            print("X",end="")
            pass
      else:
        print('exists')

274
................................................................................

In [ ]:
reporter_code_list

array([  4, 472,   8,  12,  16,  20,  24, 660,  10,  28, 899,  32,  51,
       533,  36,  40,  31,  44,  48,  50,  52, 112,  56,  58,  84, 204,
        60,  64,  68, 535,  70,  72,  74,  80,  86,  92,  76,  96, 100,
       837, 854, 108, 132, 471, 116, 120, 124, 129, 136, 140, 148, 152,
       156, 344, 446, 162, 166, 170, 174, 178, 184, 188, 384, 191, 192,
       531, 196, 203, 200, 408, 180, 208, 262, 212, 214, 588, 221, 218,
       818, 222, 226, 232, 233, 231,  97, 697, 492, 234, 238, 242, 246,
       886, 278, 866, 720, 230, 280, 582, 590, 592, 868, 717, 736, 835,
       810, 890, 836, 260, 251, 838, 254, 258, 583, 266, 270, 268, 276,
       288, 292, 300, 304, 308, 312, 316, 320, 324, 624, 328, 332, 334,
       336, 340, 348, 352, 699, 356, 360, 364, 368, 372, 376, 381, 388,
       392, 400, 398, 404, 296, 414, 417, 473, 418, 428, 422, 426, 430,
       434, 440, 442, 450, 454, 458, 462, 466, 470, 584, 474, 478, 480,
       175, 484, 496, 499, 500, 504, 508, 104, 580, 516, 520, 524, 530,
       532, 528, 536, 540, 554, 558, 562, 566, 570, 574, 637, 290, 579,
       527, 512, 577, 490, 568, 586, 585, 591, 598, 600, 459, 604, 608,
       612, 616, 620, 634, 410, 498, 636, 638, 642, 643, 646, 647, 461,
       652, 654, 659, 658, 662, 534, 666, 670, 882, 674, 678, 457, 682,
       686, 688, 891, 690, 694, 698, 702, 703, 705, 711,  90, 706, 710,
       239, 728, 724, 839, 144, 275, 729, 740, 748, 752, 757, 760, 762,
       807, 764, 626, 768, 772, 776, 780, 788, 792, 795, 796, 798, 800,
       804, 784, 826, 834, 581, 858, 849, 850, 842, 841, 860, 548, 862,
       704, 876, 879, 732,   0, 887, 894, 716])

In [ ]:
get_export(156,2022)

# Merge into mega csvs

merge_all(PATH,year_list)

In [ ]:
merge_all(PATH,year_list)

FileNotFoundError: ignored

In [ ]:
year_list

array([2019, 2020, 2021, 2022, 2023])

# Add Service data to the mega dataset

In [ ]:
get_service(year=2023)

     commodity_code dollar_value
2            010121      1894729
3            010129      5230872
4            010190          566
6            010221       129728
7            010229     65886247
...             ...          ...
5968         970300     49732604
5970         970400        55939
5972         970500        32778
5974         970600      1314343
5975         999999     27275202

[4692 rows x 2 columns]

No charts were generated by quickchart